#!/bin/bash
[ "x$1" != "x" ] || {
    echo "USAGE: $0 source-folder"
    exit 1
}

BASE=$(cd ${0%/*} && pwd -P)

cd $1

blog_title="M'uh Blog-o"
template=$(cat template/template.html)
index_markdown="$blog_title \n=="
for file in content/*
do
    html=$(markdown $file)
    title=$(head -n 1 $file)
    name=$(basename $file)

    text=${template/__CONTENT__/$html}
    text=${text/__TITLE__/$title }
    text=${text/__LINK__/$name.html}
    echo $text > $name.html

    index_markdown="$index_markdown \n\n [$title]($name.html \"$name\" )"
done

html=$( echo -e $index_markdown | markdown )
text=${template/__CONTENT__/$html}
text=${text/__TITLE__/$blog_title}
text=${text/__LINK__/}
echo $text > index.html
